# Generated by Django 3.2.10 on 2023-11-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_image',
        ),
    ]
